name = "YaoBlocksQASM"
uuid = "0d67dbe6-922f-48f4-afaf-3100500b49df"
authors = ["Arsh Sharma"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
